package com.csye6225.fall2018.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="announcement")
public class Announcement {
    private String Id;
    private String announcementId;
    private String announcementText;
    private String boardId;
    
    private Announcement() {
    	
    }
    
    public Announcement(String announcementId, String announcementText, String boardId) {
    	this.announcementId = announcementId;
    	this.announcementText = announcementText;
    	this.boardId = boardId;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() { 
    	return Id; 
    }
    
    public void setId(String Id) { 
    	this.Id = Id; 
    } 
    
    @DynamoDBIndexRangeKey(globalSecondaryIndexName="boardId-announcementId-index",attributeName="announcementId")
	public String getAnnouncementId() {
		return announcementId;
	}
	
	public void setAnnouncementId(String announcementId) {
		this.announcementId = announcementId;
	}

	@DynamoDBAttribute(attributeName="announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}

	public void setAnnouncementText(String announcementText) {
		this.announcementText = announcementText;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName="boardId-announcementId-index",attributeName="boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
    
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "announcementId=" + getAnnouncementId() + ",announcementText=" + getAnnouncementText() + ",boardId=" + getBoardId();
	}
}